### ISSUE TITLE
UNABLE TO ACTIVATE MATTERSIP IN SERVER LOGS.

### ISSUE THREAD

**Issue by naufalalishah** [bytemine/mattersip#1]
When i upload file after composing with go (.tar file 9.6 MB)  it gives me error unable to activate mattersip.Following is the error
{"level":"error","ts":1582293059.28146,"caller":"mlog/log.go:175","msg":"Unable to activate plugin","plugin_id":"net.bytemine.sip","error":"unable to start plugin: net.bytemine.sip: fork/exec /opt/bitnami/apps/mattermost/data/net.bytemine.sip/mattersip: exec format error","errorVerbose":"fork/exec /opt/bitnami/apps/mattermost/data/net.bytemine.sip/mattersip: exec format error\nunable to start plugin: net.bytemine.sip\ngithub.com/mattermost/mattermost-server/v5/plugin.(*Environment).Activate\n\tgithub.com/mattermost/mattermost-server/v5@/plugin/environment.go:270\ngithub.com/mattermost/mattermost-server/v5/app.(*App).SyncPluginsActiveState\n\tgithub.com/mattermost/mattermost-server/v5@/app/plugin.go:115\ngithub.com/mattermost/mattermost-server/v5/app.(*App).InitPlugins\n\tgithub.com/mattermost/mattermost-server/v5@/app/plugin.go:148\ngithub.com/mattermost/mattermost-server/v5/app.(*Server).RunOldAppInitialization.func6\n\tgithub.com/mattermost/mattermost-server/v5@/app/server_app_adapters.go:151\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners.func1\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:35\nsync.(*Map).Range\n\tsync/map.go:333\ngithub.com/mattermost/mattermost-server/v5/config.(*emitter).invokeConfigListeners\n\tgithub.com/mattermost/mattermost-server/v5@/config/emitter.go:33\ngithub.com/mattermost/mattermost-server/v5/config.(*commonStore).set\n\tgithub.com/mattermost/mattermost-server/v5@/config/common.go:90\ngithub.com/mattermost/mattermost-server/v5/config.(*FileStore).Set\n\tgithub.com/mattermost/mattermost-server/v5@/config/file.go:108\ngithub.com/mattermost/mattermost-server/v5/app.(*Server).UpdateConfig\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:53\ngithub.com/mattermost/mattermost-server/v5/app.(*App).UpdateConfig\n\tgithub.com/mattermost/mattermost-server/v5@/app/config.go:59\ngithub.com/mattermost/mattermost-server/v5/app.(*App).EnablePlugin\n\tgithub.com/mattermost/mattermost-server/v5@/app/plugin.go:327\ngithub.com/mattermost/mattermost-server/v5/api4.enablePlugin\n\tgithub.com/mattermost/mattermost-server/v5@/api4/plugin.go:288\ngithub.com/mattermost/mattermost-server/v5/web.Handler.ServeHTTP\n\tgithub.com/mattermost/mattermost-server/v5@/web/handlers.go:168\ngithub.com/NYTimes/gziphandler.GzipHandlerWithOpts.func1.1\n\tgithub.com/NYTimes/gziphandler@v1.1.1/gzip.go:336\nnet/http.HandlerFunc.ServeHTTP\n\tnet/http/server.go:2007\ngithub.com/gorilla/mux.(*Router).ServeHTTP\n\tgithub.com/gorilla/mux@v1.7.3/mux.go:212\nnet/http.serverHandler.ServeHTTP\n\tnet/http/server.go:2802\nnet/http.(*conn).serve\n\tnet/http/server.go:1890\nruntime.goexit\n\truntime/asm_amd64.s:1357"}

**Comment by dra** [comment]
Hi. Which version of the Mattermost server are you running exactly?

**Comment by naufalalishah** [comment]
I am using the latest version 5.20 .1  exactly .  i tried a lot to run this plugin but that error still persists

**Comment by naufalalishah** [comment]
Resolved the above issue . 
Please make a tutorial  or elaborate it will be grateful to you . secondly, https://mattermost.example.com/plugins/net.bytemine.sip/sip/<action>/<user>[?secret=<secret>]
This link is also not working giving error "authorized" .

**Comment by dra** [comment]
Glad you got it working!
