### ISSUE TITLE
Mattersip GUI

### ISSUE THREAD

**Issue by naufalalishah** [bytemine/mattersip#2]
Please Can you show the mattersip VOIP GUI ? actually i want to add with asterish server

**Comment by dra** [comment]
There is no VoIP GUI within the plugin. All VoIP configuration has to be done on your asterisk. What you have to do is configure your asterisk or your phones to send certain requests on certain events to the mattersip plugin.

**Comment by naufalalishah** [comment]
okz . Thanks a lot . will stay in touch with u  regarding this :P
