### ISSUE TITLE
unauthorized access.

### ISSUE THREAD

**Issue by naufalalishah** [bytemine/mattersip#3]
**All the things are working really good except this last one @dra** 
https://127.0.0.1:5000/plugins/net.bytemine.sip/sip/login/Naufal[?secret=%3Csecret%3E]

Whenever i put this above url in browser it gives me error **unauthorized**. Kindly plz help me to sort out the issue . I am using the following settings in mattersip
Teamname: Naufal
Secret : *********
Number-User Mappings: 112:Naufal

Is there any futher settings or any permissions that i have to gave ? Thanks in advance

**Comment by dra** [comment]
But you did replace the "secret" param with your password, correct? Asuming your password is "hellopassword" your URL to call would be

https://127.0.0.1:5000/plugins/net.bytemine.sip/sip/login/Naufal?secret=hellopassword

**Comment by naufalalishah** [comment]
Obviously, i replaced the password but i forget to remove the brackets from the end [ ] these one Anyway . 
**Now i put the link exactly above now it is showing blank Page** 
I  think i am alomost done  and in the logs it is showing following below
{"level":"error","ts":1582885883.7819283,"caller":"mlog/sugar.go:23","msg":"request url parts: []string{\"dnd-on\", \"Naufal\"}","plugin_id":"net.bytemine.sip"}

{"level":"info","ts":1582885883.806956,"caller":"mlog/sugar.go:19","msg":"send message to","plugin_id":"net.bytemine.sip","channel":"cm7cc8nd5pdy3nssk88te18k6c"}

**Comment by dra** [comment]
I am passing this to my colleague who wrote the plugin, he will have at it during next week.
