### ISSUE TITLE
More use case

### ISSUE THREAD

**Issue by gamersalpha** [bytemine/mattersip#4]
Hello look very cool, but how that's works, please ?
need to know more information ?

**Comment by dra** [comment]
Hm, it should get clear from the how-to: compile the plugin, upload it to your Mattermost server, and configure your phone server or phones to call a plugin URL on certain actions.

**Comment by COFIEM-Informatique** [comment]
it's a bit obscure :-) . if I understand the plugin show the agent status. But it doen't not act as softphone ?

**Comment by bytemine-gmbh** [comment]
It is not a softphone, it has no ability to initiate, route or handle calls. This quite outdated plugin just reads status information from phones attached to a PBX.
